---

- name: generate locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: set locale
  become: true
  shell: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8

#- name: reboot host
#  shell: sleep 2 && reboot
#  async: 1
#  poll: 0
#  ignore_errors: true
#
#- name: wait to host up
#  wait_for:
#    host: "{{ inventory_hostname }}"
#    port: 22
#    state: started
#    delay: 10
#    timeout: 300
#  connection: local
